name: Build, Push to Docker Hub & GCP, then Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- Authenticate to Docker Hub ---
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # --- Authenticate to Google Cloud ---
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for GCP Artifact Registry
        run: gcloud auth configure-docker asia-south2-docker.pkg.dev

      # --- Build and Multi-Push ---
      - name: Build and Push Images
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            shivangs107/book-recommender:latest
            shivangs107/book-recommender:${{ github.sha }}
            asia-south2-docker.pkg.dev/recommender-book/book-recommender/book-recommender:latest
            asia-south2-docker.pkg.dev/recommender-book/book-recommender/book-recommender:${{ github.sha }}

      # --- Deploy to Cloud Run (using GCP image) ---
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy book-recommender \
            --image asia-south2-docker.pkg.dev/recommender-book/book-recommender/book-recommender:latest \
            --region asia-south2 \
            --platform managed \
            --allow-unauthenticated \
            --port 7860 \
            --memory 3Gi \
            --cpu 1